import FooterComponent from "../components/footer/page";
import HeaderComponent from "../components/header/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderComponent />

        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
