import { Metadata } from "next";
import FooterComponent from "../components/footer/page";
import HeaderComponent from "../components/header/page";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    // absolute: "",
    default: "Next.js Tutorial",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <HeaderComponent />

          {children}
          <FooterComponent />
        </body>
      </ThemeProvider>
    </html>
  );
}
