import { Metadata } from "next";
import FooterComponent from "../components/footer/page";
import HeaderComponent from "../components/header/page";

export const metadata: Metadata = {
  title: {
    // absolute: "",
    default: "Next.js Tutorial",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderComponent />

        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
